# Generated by Django 5.0.2 on 2024-02-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
    ]
